# 端口配置
server:
  port: 9103
spring:
  application:
    name: spring-docker-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/db_test?characterEncoding=utf8
    username: root
    password: ENC(pwb04a/MdkhIK3WyYZGDlVBw==)
