server:
  port: 91021
spring:
  application:
    name: coding
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.159.160:3306/db_test?characterEncoding=utf8&useSSL=false
    username: coding
    password: xxx
